name = "PrimeCert"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["PrimeCert"]
testDriver = "PrimeCertTest"

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "8df0e1b604d1668165ad022c4bc8be3fe03e6efd"

[[lean_lib]]
name = "PrimeCert"

[[lean_lib]]
name = "PrimeCertTest"
globs = ["PrimeCertTest.+"]
