name = "PrimeCert"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["PrimeCert"]
testDriver = "PrimeCertTest"

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "8f5331973a3e2b3cc5fd307208f456ccd6d3b467"

[[lean_lib]]
name = "PrimeCert"

[[lean_lib]]
name = "PrimeCertTest"
globs = ["PrimeCertTest.+"]
