name = "PrimeCert"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["PrimeCert"]
testDriver = "PrimeCertTest"

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "db584cd6d46c92f209a44c0f1c829460d327499d"

[[lean_lib]]
name = "PrimeCert"

[[lean_lib]]
name = "MillerRabin"
globs = ["MillerRabin.+"]

[[lean_lib]]
name = "PrimeCertTest"
globs = ["PrimeCertTest.+"]
