

# This file was *autogenerated* from the file make-certificate.sage
from sage.all_cmdline import *   # import sage library

n=int(input("Please input a prime number to be certified:"))
print("Number received: n=%d"%n)
if not n in Primes():
	print("It is not prime.")
	sys.exit()

