/-
Copyright (c) 2025 Kenny Lau, Bhavik Mehta. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenny Lau, Bhavik Mehta
-/
module

public import Lean.Elab.Command
public meta import Mathlib.Data.Nat.Prime.Defs
import Mathlib.Tactic.NormNum.Prime

/-! # Primality proofs for small primes

Primes 2–3000 are generated by `norm_num` via the `make%` macro (which takes the upper
bound), supplying the `PrimeCert.prime_N` declarations used by the `small` certificate method.
-/

public section

namespace PrimeCert

local elab "make%" hi:num : command => do
  for i in Array.range' 2 (hi.getNat - 1) do
    if Nat.Prime i then
      have iStx := Lean.Syntax.mkNatLit i
      have name := Lean.mkIdent <| Lean.Name.mkSimple s!"prime_{i}"
      Lean.Elab.Command.elabCommand =<< `(command| theorem $name : Nat.Prime $iStx := by norm_num)

make% 3000

/-- info: PrimeCert.prime_2 : Nat.Prime 2 -/
#guard_msgs in
#check prime_2

/-- info: PrimeCert.prime_997 : Nat.Prime 997 -/
#guard_msgs in
#check prime_997

end PrimeCert

end
